package SEMESTER5;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.event.KeyEvent;
/**
 *
 * @author User
 */
public class Tugas2 extends javax.swing.JFrame {

    /**
     * Creates new form Tugas2
     */
    public Tugas2() {
        initComponents();
        setupEvents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        inputField = new javax.swing.JTextField();
        inputLabel = new javax.swing.JLabel();
        dariLabel = new javax.swing.JLabel();
        dariComboBox = new javax.swing.JComboBox<>();
        keLabel = new javax.swing.JLabel();
        keComboBox = new javax.swing.JComboBox<>();
        hasilLabel = new javax.swing.JLabel();
        hasilField = new javax.swing.JTextField();
        KonversiButton = new javax.swing.JButton();
        manualRadio = new javax.swing.JRadioButton();
        autoRadio = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setText("APLIKASI KONVERSI SUHU");

        inputLabel.setText("Masukkan Suhu");

        dariLabel.setText("Dari");

        dariComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));
        dariComboBox.setSelectedIndex(1);

        keLabel.setText("Ke");

        keComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));
        keComboBox.setSelectedIndex(1);

        hasilLabel.setText("Hasil Konversi");

        hasilField.setEditable(false);

        KonversiButton.setText("KONVERSI");

        buttonGroup1.add(manualRadio);
        manualRadio.setSelected(true);
        manualRadio.setText("Konversi Manual");

        buttonGroup1.add(autoRadio);
        autoRadio.setText("Konversi Otomatis");
        autoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(inputLabel)
                                .addGap(64, 64, 64)
                                .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dariLabel)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(hasilLabel)
                                        .addGap(34, 34, 34))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dariComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(hasilField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(keLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(keComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(manualRadio)
                        .addGap(44, 44, 44)
                        .addComponent(autoRadio)))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(KonversiButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(titleLabel)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(titleLabel)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLabel)
                    .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dariLabel)
                    .addComponent(dariComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keLabel)
                    .addComponent(keComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasilLabel)
                    .addComponent(hasilField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(KonversiButton)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manualRadio)
                    .addComponent(autoRadio))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void setupEvents() {
        KonversiButton.addActionListener(evt -> konversiSuhu());

        inputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!((c >= '0' && c <= '9') || c == '.' || c == '-' ||
                        c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
                    evt.consume();
                    getToolkit().beep();
                }
                if (c == '.' && inputField.getText().contains(".")) {
                    evt.consume();
                    getToolkit().beep();
                }
    
                if (c == '-' && inputField.getText().length() > 0) {
                    evt.consume();
                    getToolkit().beep();
                }
            }
        });

        manualRadio.addItemListener(evt -> {
            if (autoRadio.isSelected()) {
                KonversiButton.setEnabled(false);
                konversiSuhu();
            } else {
                KonversiButton.setEnabled(true);
            }
        });

        autoRadio.addItemListener(evt -> {
            if (autoRadio.isSelected()) {
                konversiSuhu();
                KonversiButton.setEnabled(false);
            } else {
                KonversiButton.setEnabled(true);
            }
        });

        dariComboBox.addItemListener(evt -> {
            if (autoRadio.isSelected()) konversiSuhu();
        });

        keComboBox.addItemListener(evt -> {
            if (autoRadio.isSelected()) konversiSuhu();
        });

        inputField.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent evt) { if (autoRadio.isSelected()) konversiSuhu(); }
            public void removeUpdate(DocumentEvent evt) { if (autoRadio.isSelected()) konversiSuhu(); }
            public void changedUpdate(DocumentEvent evt) { if (autoRadio.isSelected()) konversiSuhu(); }
        });
    }

    private void konversiSuhu() {
        try {
            String inputText = inputField.getText().trim();
            if (inputText.isEmpty() || inputText.equals("-") || inputText.equals(".")) {
                hasilField.setText("");
                return;
            }

            double suhuInput = Double.parseDouble(inputText);
            String dariSkala = (String) dariComboBox.getSelectedItem();
            String keSkala = (String) keComboBox.getSelectedItem();

            double suhuCelcius = konversiKeCelcius(suhuInput, dariSkala);
            double hasil = konversiDariCelcius(suhuCelcius, keSkala);

            hasilField.setText(String.format("%.2f °%s", hasil, keSkala.substring(0, 1)));
        } catch (NumberFormatException ex) {
            hasilField.setText("Input tidak valid");
        }
    }

    private double konversiKeCelcius(double suhu, String dariSkala) {
        return switch (dariSkala) {
            case "Fahrenheit" -> (suhu - 32) * 5 / 9;
            case "Reamur" -> suhu * 5 / 4;
            case "Kelvin" -> suhu - 273.15;
            default -> suhu;
        };
    }

    private double konversiDariCelcius(double suhuCelcius, String keSkala) {
        return switch (keSkala) {
            case "Fahrenheit" -> (suhuCelcius * 9 / 5) + 32;
            case "Reamur" -> suhuCelcius * 4 / 5;
            case "Kelvin" -> suhuCelcius + 273.15;
            default -> suhuCelcius;
        };
    }

    private void autoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoRadioActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> new Tugas2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KonversiButton;
    private javax.swing.JRadioButton autoRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> dariComboBox;
    private javax.swing.JLabel dariLabel;
    private javax.swing.JTextField hasilField;
    private javax.swing.JLabel hasilLabel;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> keComboBox;
    private javax.swing.JLabel keLabel;
    private javax.swing.JRadioButton manualRadio;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
