package SEMESTER5;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author User
 */
public class Tugas1 extends javax.swing.JFrame {

    /**
     * Creates new form Tugas1
     */
    public Tugas1() {
        initComponents();
        setupEventListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        inputLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        checkButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        primeCheckBox = new javax.swing.JCheckBox();
        numberField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setText("APLIKASI CEK NOMOR GENAP/GANJIL");

        inputLabel.setText("Masukkan Angka");

        resultLabel.setText("Untuk Menampilkan Hasil");

        checkButton.setText("CEK");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        primeCheckBox.setText("CEK JUGA BILANGAN PRIMA");
        primeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeCheckBoxActionPerformed(evt);
            }
        });

        numberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                .addComponent(numberField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(checkButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addComponent(titleLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(primeCheckBox)))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(titleLabel)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLabel)
                    .addComponent(numberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(resultLabel)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkButton)
                    .addComponent(clearButton))
                .addGap(27, 27, 27)
                .addComponent(primeCheckBox)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        // TODO add your handling code here:
        String input = numberField.getText().trim();

    if (input.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Masukkan angka terlebih dahulu!",
                "Input Kosong",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        long number = Long.parseLong(input);
        String result = checkEvenOdd(number);

        if (primeCheckBox.isSelected()) {
            result += " | " + checkPrime(number);
        }

        resultLabel.setText(result);

        JOptionPane.showMessageDialog(this,
                "Angka " + number + " adalah:\n" + result,
                "Hasil Pengecekan",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Input harus berupa angka bulat!",
                "Input Tidak Valid",
                JOptionPane.ERROR_MESSAGE);
        clearButtonActionPerformed(evt);
    }
    //GEN-LAST:event_checkButtonActionPerformed
    }//GEN-LAST:event_checkButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        numberField.setText("");
        resultLabel.setText("Hasil akan ditampilkan di sini");
        resultLabel.setForeground(new Color(0, 0, 0));
        primeCheckBox.setSelected(false);
        numberField.requestFocus();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void primeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeCheckBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_primeCheckBoxActionPerformed

    private void numberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberFieldActionPerformed

    // =====================================================
    // FUNGSI TAMBAHAN
    // =====================================================
    private void setupEventListeners() {
        // Membatasi input hanya angka
        numberField.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!(Character.isDigit(c) || c == '-' || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
                    evt.consume();
                    getToolkit().beep();
                }
                if (c == '-' && numberField.getText().length() > 0) {
                    evt.consume();
                    getToolkit().beep();
                }
            }
        });
    }

    private String checkEvenOdd(long number) {
        if (number % 2 == 0) {
            resultLabel.setForeground(Color.BLUE);
            return "Bilangan GENAP";
        } else {
            resultLabel.setForeground(Color.RED);
            return "Bilangan GANJIL";
        }
    }

    private String checkPrime(long number) {
        if (number < 2) return "Bukan Prima";
        if (number == 2) return "Prima";
        if (number % 2 == 0) return "Bukan Prima";

        for (long i = 3; i * i <= number; i += 2) {
            if (number % i == 0) return "Bukan Prima";
        }
        return "Prima";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> {
            new Tugas1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JTextField numberField;
    private javax.swing.JCheckBox primeCheckBox;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
